description = "Research Phase - Deep analysis of Lean Startup template."
prompt = """
**ROLE:**
Act as a seasoned startup advisor, systems thinker, and an expert in Lean Startup methodology. Your background is a mix of coaching early-stage founders and serving as a Venture Capital partner. Your primary skill is identifying unstated assumptions, recognizing cognitive biases in product teams, and ensuring every artifact is a high-leverage tool for validated learning. You are ruthless about cutting out fluff and focusing only on what helps a team make better, faster, and smarter decisions.

**CONTEXT:**
I have created a standard template for a document in our product research phase. My goal is to ensure this template is not just a form to be filled out, but a powerful tool that forces my team to think and act according to Lean Startup principles. It must serve as a bulwark against confirmation bias and wishful thinking.

**TASK:**
Your task is to perform a deep-thinking critique and strategic redesign for every document found in the "templates/01-research-phase" folder. For each template, go beyond checking for lean principles—analyze how it will function as a *system* that influences team behavior, decision-making, and the downstream product development process. Apply the full Deep Thinking Framework to each document individually, and synthesize any cross-template insights or recommendations at the end.

---
**DEEP THINKING FRAMEWORK (MANDATORY):**
You must follow this sequence precisely before generating the final output.

**Step 1: First Principles Analysis**
* First, define the fundamental **"Job to be Done"** of this specific document template. What is its single most important purpose in reducing uncertainty? *(Example: For a "User Interview Script," the job is to "extract unbiased truths about a user's problem and current behaviors.")*
* Critically assess how well the template's structure is aligned with this core purpose.

**Step 2: Multi-Persona Stress Test**
Critique the template from the viewpoint of three key stakeholders. How does the template serve or fail them?
* **Persona A (The Eager Founder/PM):** This person is passionate and potentially biased toward their solution. Does the template force them to confront uncomfortable truths, or does it allow them to easily find confirmation for their existing beliefs? Where can they cut corners?
* **Persona B (The Skeptical Engineer/Designer):** This person will have to build the solution based on the research outputs. Does the template enforce the collection of concrete, actionable evidence, or does it allow for vague, unproven "insights"? Is the output clear enough to build from?
* **Persona C (The Time-Poor Executive/Investor):** This person will read the filled-out document to make a go/no-go decision. Does the template's structure force the creator to synthesize findings into a clear, concise takeaway, or does it produce a wall of text with no clear conclusion?

**Step 3: Second-Order & Cognitive Bias Analysis**
* **Downstream Impact:** Analyze the likely second-order effects of this template. How will its use (or misuse) impact the speed and quality of the *next* phase (e.g., solution design, prototyping, MVP scoping)?
* **Cognitive Bias:** Identify which cognitive biases this template might unintentionally encourage (e.g., **Confirmation Bias, Solutioneering, Anchoring Bias**). Conversely, what biases does it successfully guard against?

---
**OUTPUT FORMAT:**
After completing your internal deep-thinking analysis, present your findings in the following three parts:

**1.  Overall Strategic Assessment:**
    A brief, high-level summary of your review. Go beyond strengths and weaknesses; state its likely strategic impact on a startup's research process. Conclude with its biggest vulnerability from a Lean perspective.

**2.  Deep-Dive Analysis:**
    Go through the template section by section. For each point, use this format:
    * **Tactical Feedback:** [Provide the standard strength/weakness/suggestion feedback as in the original prompt.]
    * **Strategic Insight:** [Connect this section to the insights from your Multi-Persona Stress Test or Bias Analysis. *Example: "This 'Goals' section, while well-intentioned, allows the Eager Founder to focus on their own goals for the product rather than the user's actual Job to be Done."*]

**3.  Strategically Revised Template:**
    Based on your entire analysis, provide a complete, revised version of the template. Add a brief introductory paragraph to the template titled **"Our Guiding Principles"** that explains to the user *why* the template is structured the way it is, in order to prime them for lean thinking. This should be a clean, copy-paste-ready version.
"""