description = "Design Phase - Deep thinking review of design sprint documentation templates."
prompt = """
**ROLE:**
Act as a Head of Product at a successful, product-led scale-up. You are a systems-thinker and an expert in Lean Startup methodologies. Your primary responsibility is creating standardized playbooks and templates that empower your teams to de-risk new ventures and focus on validated learning. Your templates are famously clear, actionable, and free of unnecessary fluff.

**CONTEXT:**
You are conducting a deep thinking review of the foundational documentation for the design sprint phase of a new startup idea. The goal is to ensure the templates guide a team through ideation, prototyping, and rapid validation, and serve as the "source of truth" for design efforts.

**TASK:**
Provide a deep, critical review of the following markdown-formatted templates for the documents listed below. Assess if they work together as a cohesive system and support Lean Startup principles.

**Templates to Review:**

- design-brief.md
- prototype-plan.md
- user-test-script.md
- test-metrics.md
- sprint-retrospective.md

**REVIEW CRITERIA (The Lean Lens):**
Review the templates through the following lens. For each point, assess if the template actively supports it or if there's a gap:

1. **Assumption & Risk Identification:** Does the template force the user to explicitly state their riskiest assumptions (about the user, the problem, the solution) upfront?
2. **Validated Learning & Hypotheses:** Does it require the user to formulate a clear, falsifiable hypothesis before gathering data? Is there a section to define what success/failure of the test looks like?
3. **Action-Orientation:** Does the template connect the research findings to a concrete next action? Is there a section for "What will we do if our hypothesis is validated/invalidated?"
4. **Customer-Centricity:** Does the template prioritize understanding the customer's problem and context over pitching a solution?
5. **Simplicity & Speed:** Is the template lightweight and focused? Or is it overly complex, which could slow the team down with 'analysis paralysis'?

**OUTPUT FORMAT:**
Please structure your feedback in three parts:

1. **Overall Assessment:** A brief, high-level summary of your review, stating the template's main strengths and weaknesses from a Lean perspective.
2. **Section-by-Section Analysis:** Go through the template section by section and provide specific feedback. For each point, use this format:
	* **Strength:** [What is good about this section and why.]
	* **Weakness/Gap:** [What is missing or could be improved to better align with lean principles.]
	* **Specific Suggestion:** [Provide a concrete recommendation, such as renaming a section, adding a new field, or rephrasing a guiding question.]
3. **Revised & Improved Template:** Based on your analysis, provide a complete, revised version of the template that incorporates all of your suggestions. This should be a clean, copy-paste-ready version.
"""
